### ISSUE TITLE
Incorrect mission types

### ISSUE THREAD

**Issue by pblivingston** [rolfosian/drgmissions#12]
Some mission types are incorrect. For example, at this timestamp: 
"2024-06-23T02:30:00Z"
two missions in Dense Biozone show incorrect mission types. In game, "Burning Fort" is a Salvage with Glyphid Eggs, but shown here as Elimination. "Total Desert" is an Escort with Fossils, but shown as Salvage with Hollomite. Most missions are entirely correct, but it seems like there are a few like this in every batch.

**Comment by rolfosian** [comment]
I looked at the timestamp on a fresh table and It looks like GSG has just barely tweaked the generator in the latest patch so unfortunately the data has gone a little stale. Thanks for bringing this to my attention, I'll run the scraper again and update the json. Maybe I will write some stuff to automate checking for new builds and compare a couple of rotations of new data with the old to see if things have gone stale or not as soon as a new build is pushed? It shouldn't be long until things settle down though.
