### ISSUE TITLE
Minor errors in current missions

### ISSUE THREAD

**Issue by PinkPhoton** [rolfosian/drgmissions#4]
I found a couple errors for the missions at 5:30 PM GMT, 3/17/2024. (Happy Saint Patrick's Day, miners!)
The website shows a double-XP Point Extraction mission, but in the game the mission also has a Lithophage outbreak. Also, the website only lists 3 missions in the Salt Pits.
![DRG mission error](https://github.com/rolfosian/drgmissions/assets/63066473/986b94f8-a6dc-40a3-8234-288a66eeb68c)

**Comment by rolfosian** [comment]
This is a duplicate issue of this one here:

https://github.com/rolfosian/drgmissions/issues/2#issuecomment-1857163275

I'll probably look into making more scripts and set up some kind of multiple virtual machine script for scraping different seasons concurrently + new endpoints and new pages for different season toggles when the Season 5 patch hits as GSG said they're looking into making content toggles for all seasons, but for now all of the data is with the season 4 content toggled off.
